---

- name: Ensure config dir exists
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_gid}}"
  loop: 
    - "{{ansible_env.HOME}}/.config/containers"
    - "{{ansible_env.HOME}}/.config/containers/systemd"

- name: Load OS-specific vars.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_facts.distribution}}.yml'
        - '{{ansible_facts.os_family}}.yml'
        - main.yml
      paths:
        - 'vars'

- include_tasks: setup-Debian.yml
  when: ansible_facts.os_family == 'Debian'

# copy containers config file to the server
- name: Deploy containers config file
  template:
    src: containers.conf.j2
    dest: "{{ansible_env.HOME}}/.config/containers/containers.conf"

# update net.ipv4.ip_unprivileged_port_start=80 in sysctl.conf
- name: Ensure net.ipv4.ip_unprivileged_port_start is set to 80
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: 80
    state: present
    reload: yes
  become: true
