---

- name: start the post services
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "{{ item.state | default('started') }}"
    command: "{{ item.command | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    restart: "{{ item.restart | default(omit)}}"
    env: "{{ item.env | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    networks: "{{ item.networks | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    etc_hosts: "{{ item.extra_hosts | default(omit) }}"
    docker_host: "{{ docker_host }}"
