---

# include the config files
- include_tasks: config-files.yml

# create docker network if not exists
- name: Create Docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present
    docker_host: "{{ docker_host }}"

# adding volumes for services
- name: create volumes
  community.docker.docker_volume:
    name: "{{ item.name }}"
    state: present
    driver: "{{ item.driver | default(omit) }}"
    driver_options: "{{ item.driver_options | default(omit) }}"
    docker_host: "{{ docker_host }}"
  loop: "{{ services_volumes | default([]) }}"


- name: "Deploy Quadlet container units "
  ansible.builtin.template:
    src: container.container.j2
    dest: "{{ ansible_env.HOME }}/.config/containers/systemd/container.{{ item.name }}.container"
    mode: "0644"
  notify: Reload Systemd
  loop: "{{ services + sites }}"

- meta: flush_handlers  # <- forces the "Reload Systemd" handler to run immediately

- name: "Enable and start containers systemd service"
  ansible.builtin.systemd:
    name: "container.{{ item.name }}.service"
    scope: user
    enabled: true
    state: started
  loop: "{{ services + sites }}"

# # include services
# - name: include services
#   include_tasks: podman-containers.yml
#   loop: "{{ services }}"

# # include sites with tag 'sites'
# - name: include sites
#   include_tasks: podman-containers.yml
#   loop: "{{ sites }}"
#   tags: sites