---

- name: Restart RedisExporter
  ansible.builtin.systemd:
    name: container.redis-exporter.service
    state: restarted
    scope: user

- name: Restart Promtail
  ansible.builtin.systemd:
    name: container.promtail.service
    state: restarted
    scope: user
