# Workflow: playbook-run
# Trigger: repository_dispatch with type 'playbook-run'
# Required inputs in client_payload:
#   - role_tag: tag of the role to run


name: repository-dispatch-playbook-run

permissions:
  id-token: write
  contents: read

on:
  repository_dispatch:
    types: [playbook-run]

concurrency:
  group: "playbook-run"
  cancel-in-progress: false

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      # Checkout the infra repo itself
      - name: Checkout Repo
        uses: actions/checkout@v4

      # set up python to install ansible
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Ansible virtualenv
        id: cache-ansible
        uses: actions/cache@v4
        with:
          path: .venv
          key: ansible-${{ runner.os }}-${{ hashFiles('requirements.yml') }}

      - name: Install Ansible (if cache miss)
        if: steps.cache-ansible.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install -r requirements.yml

      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2 # Use the latest stable version
        with:
          method: jwt
          jwtGithubAudience: vault
          url: https://vault.same3na.com
          role: github-infra-role 
          secrets: |
            kv/data/same3na/dev/server PRIVATE_KEY | PRIVATE_KEY ;
            kv/data/same3na/dev/server DB_PASS | DB_PASS ;

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.PRIVATE_KEY }}

      # - name: Verify SSH Connection
      #   run: |
      #     ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.pass

      # Run the ansible playbook with the specified tag
      - name: Run Ansible Playbook
        env:
          DB_PASSWORD: ${{ env.DB_PASS }}
          VAULT_TOKEN:  nowaykhosay
        run: |
          source .venv/bin/activate
          ansible-playbook -i provisioning/inventory/ provisioning/playbook-dev.yml \
          --tags "${{ github.event.inputs.role_tag }}" \
          --vault-password-file vault_pass.pass