name: update-image-tag

on:
  repository_dispatch:
    types: [update-image-tag]

concurrency:
  group: "infra-tag-update"
  cancel-in-progress: false

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      # Checkout the infra repo itself
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.UPDATE_INFRA_TOKEN }}

      # Validate inputs
      - name: Validate project_name exists
        run: |
          if ! grep -q "^${{ github.event.client_payload.project_name }}_docker_version:" provisioning/inventory/group_vars/dev/containers.yml; then
            echo "Project ${{ github.event.client_payload.project_name }} not found in containers.yml"
            exit 1
          fi

      # Update the image tag in the YAML file
      - name: Update image tag
        run: |
          echo "Updating project ${{ github.event.client_payload.project_name }} to tag ${{ github.event.client_payload.image_tag }}"
          sed -i "s|^${{ github.event.client_payload.project_name }}_docker_version:.*|${{ github.event.client_payload.project_name }}_docker_version: ${{ github.event.inputs.image_tag }}|" provisioning/inventory/group_vars/dev/containers.yml

      # Commit & push changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add vars/images.yaml
          git commit -m "Update ${{ github.event.client_payload.project_name }} image tag to ${{ github.event.client_payload.image_tag }}" || echo "No changes to commit"
          git push

