name: workflow-dispatch-playbook-run

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      role_tag:
        description: 'The ansible playbook tag to run'
        required: true
        type: string

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      # Checkout the infra repo itself
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Dispatch playbook-run event
        uses: ./.github/actions/run-playbook
        with:
          role_tag: sites